stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "This job is triggered manually"
    - apt-get update
    - apt-get install awscli -y
    - aws --version
    - apt-get install -y jq
    - jq --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region us-east-1

    # Run the AWS CLI command to assume the role.
    - aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name GitLabCIAssumeRole >temp-cred-file
    - cat temp-cred-file
    # Export the assumed role's temporary credentials.
    - aws configure set aws_access_key_id $(cat temp-cred-file | jq '.Credentials' | jq '.AccessKeyId' -r) --profile temp-profile
    - aws configure set aws_secret_access_key $(cat temp-cred-file| jq '.Credentials' | jq '.SecretAccessKey' -r) --profile temp-profile
    - aws configure set aws_session_token $(cat temp-cred-file | jq '.Credentials' | jq '.SessionToken' -r) --profile temp-profile
    - aws configure set default.region us-east-1 --profile temp-profile
    - rm -rf temp-cred-file
    # Now you can use the assumed role credentials for AWS CLI commands.
    - aws s3 ls --profile temp-profile
    - aws cloudformation create-stack --stack-name example --template-body file://step-function-cft.yaml --capabilities CAPABILITY_IAM --region us-east-1 --profile temp-profile
    - aws cloudformation wait stack-create-complete --stack-name example --region us-east-1 --profile temp-profile
  when: manual

