AWSTemplateFormatVersion: "2010-09-09"
Description: 'AWS Batch via Fargate'

Parameters:
  ComputeEnvironment:
    Type: String
    Description: ARN of the AWS Batch Compute Environment

  ImageName:
    Type: String
    Description: Name of the Docker image

  JobRoleArn:
    Type: String
    Description: ARN of the IAM role for the job

  ExecutionRoleArn:
    Type: String
    Description: ARN of the IAM role for execution

Resources:
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnvironment
          Order: 1
      Priority: 1
      State: ENABLED

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Ref AWS::StackName
      PlatformCapabilities:
        - FARGATE
      Timeout:
        AttemptDurationSeconds: 60
      RetryStrategy:
        Attempts: 1
      ContainerProperties:
        Command:
          - echo
          - hello
          - world
        Image: !Ref ImageName
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        ResourceRequirements:
          - Type: VCPU
            Value: 0.5
          - Type: MEMORY
            Value: 1024
        JobRoleArn: !Ref JobRoleArn
        ExecutionRoleArn: !Ref ExecutionRoleArn



aws cloudformation create-stack \
  --stack-name YourBatchStack \
  --template-body file://your-template-file.yaml \
  --parameters ParameterKey=ComputeEnvironment,ParameterValue=arn:aws:batch:your-region:your-account-id:compute-environment/your-compute-env \
               ParameterKey=ImageName,ParameterValue=your-docker-image-name \
               ParameterKey=JobRoleArn,ParameterValue=arn:aws:iam::your-account-id:role/your-job-role \
               ParameterKey=ExecutionRoleArn,ParameterValue=arn:aws:iam::your-account-id:role/your-execution-role \
  --capabilities CAPABILITY_IAM
