Resources:

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      ComputeEnvironmentOrder:
        - ComputeEnvironment

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties: 
      Type: container
      ContainerProperties:
        Image: busybox
        Vcpus: 2
        Memory: 512      

  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !Ref BatchServiceRole
      ComputeResources:
        Type: FARGATE
        MinvCpus: 0
        MaxvCpus: 2
        DesiredvCpus: 2
        Subnets: 
          - subnet-xxxxxxx
        SecurityGroupIds:
          - sg-xxxxxxx   

  BatchJob:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinition: !Ref BatchJobDefinition
      JobQueue: !Ref BatchJobQueue
      ContainerOverrides:
        Command:
          - echo
          - "Hello World"
