Parameters:
  RepositoryName:
    Type: String
    Description: Name of the ECR repository

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
aws cloudformation create-stack   --stack-name YourECRStack   --template-body file://ecr-cft.yaml   --parameters ParameterKey=RepositoryName,ParameterValue=test-repo-2
