Parameters:
  RepositoryName:
    Type: String
    Description: Name of the ECR repository

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
