AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyGlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: MyGlueJob
      Role: arn:aws:iam::123456789012:role/YourGlueServiceRole
      Command:
        Name: glueetl
        ScriptLocation: s3://your-s3-bucket/your-glue-script.py
      DefaultArguments:
        "--job-language": python
        "--extra-py-files": s3://your-s3-bucket/your-python-dependency.zip
      GlueVersion: "4.0"
      WorkerType: G.2X
      NumberOfWorkers: 2
      MaxCapacity: 2.0
