AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  GlueConnectionName:
    Type: String
    Description: Name of the Glue Connection

  GlueRoleArn:
    Type: String
    Description: ARN of the IAM role for the Glue job

  GlueScriptLocation:
    Type: String
    Description: S3 path to the Glue ETL script

  ExtraPyFiles:
    Type: String
    Description: S3 path to the Glue ETL script

Resources:
  MyGlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: MyGlueJob
      Role: !Ref GlueRoleArn
      Command:
        Name: glueetl
        ScriptLocation: !Ref GlueScriptLocation
      DefaultArguments:
        '--job-bookmark-option': 'job-bookmark-disable'
        '--key1': 'value1'
        '--key2': 'value2'
        '--TempDir': 's3://your-s3-bucket/temp-path/'
        '--job-language': 'python'
        '--enable-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-spark-ui': 'true'
        '--spark-event-logs-path': 's3://your-s3-bucket/spark-logs/'
        '--extra-py-files': !Ref ExtraPyFiles
        '--connection-name': !Ref GlueConnectionName

      GlueVersion: "4.0"
      WorkerType: G.2X
      NumberOfWorkers: 10


aws cloudformation create-stack \
  --stack-name YourGlueJobStack \
  --template-body file://path/to/your/template.yaml \
  --parameters ParameterKey=GlueConnectionName,ParameterValue=YourConnectionName \
               ParameterKey=GlueRoleArn,ParameterValue=arn:aws:iam::your-account-id:role/YourGlueRole \
               ParameterKey=GlueScriptLocation,ParameterValue=s3://your-s3-bucket/your-glue-script.py \
               ParameterKey=ExtraPyFiles,ParameterValue=



stages:
  - deploy

variables:
  STACK_NAME: YourGlueJobStack
  TEMPLATE_FILE: path/to/your/template.yaml
  AWS_DEFAULT_REGION: your-region
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Set your AWS credentials in GitLab CI/CD environment variables
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  GLUE_CONNECTION_NAME: YourConnectionName
  GLUE_ROLE_ARN: arn:aws:iam::your-account-id:role/YourGlueRole
  GLUE_SCRIPT_LOCATION: s3://your-s3-bucket/your-glue-script.py
  EXTRA_PY_FILES: ''

deploy_stack:
  stage: deploy
  script:
    - |
      if aws cloudformation describe-stacks --stack-name $STACK_NAME 2>/dev/null; then
        echo "Stack already exists. Skipping stack creation."
      else
        aws cloudformation create-stack \
          --stack-name $STACK_NAME \
          --template-body file://$TEMPLATE_FILE \
          --parameters ParameterKey=GlueConnectionName,ParameterValue=$GLUE_CONNECTION_NAME \
                       ParameterKey=GlueRoleArn,ParameterValue=$GLUE_ROLE_ARN \
                       ParameterKey=GlueScriptLocation,ParameterValue=$GLUE_SCRIPT_LOCATION \
                       ParameterKey=ExtraPyFiles,ParameterValue=$EXTRA_PY_FILES
      fi
