AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS Glue Database

Parameters:
  DatabaseName:
    Type: String
    Description: Name of the Glue Database

Resources:
  MyGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName

aws cloudformation create-stack   --stack-name YourGlueDatabaseStack   --template-body file://glue-databse-cft.yaml   --parameters ParameterKey=DatabaseName,ParameterValue=test-db


=======================================

AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS Glue Table for Athena

Parameters:
  DatabaseName:
    Type: String
    Description: Name of the Glue Database
  TableName:
    Type: String
    Description: Name of the Glue Table
  S3Location:
    Type: String
    Description: S3 location of the data

Resources:
  MyGlueTable:
    Type: AWS::Glue::Table
    Properties:
      DatabaseName: !Ref DatabaseName
      CatalogId: !Ref AWS::AccountId
      TableInput:
        Name: !Ref TableName
        StorageDescriptor:
          Columns:
            - Name: column1
              Type: string
            - Name: column2
              Type: int
          Location: !Ref S3Location
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
          Parameters:
            classification: json
            compressionType: none


aws cloudformation create-stack   --stack-name GlueTableStack   --template-body file://aws-glue-table-cft.yaml   --parameters ParameterKey=DatabaseName,ParameterValue=test-db ParameterKey=TableName,ParameterValue=table-name ParameterKey=S3Location,ParameterValue=s3://your-s3-bucket/path/to/data
