AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a Step Functions state machine.

Parameters:
  StateMachineName:
    Type: String
    Default: HelloWorld-StateMachine
    Description: Name of the Step Functions state machine

  RoleArn:
    Type: String
    Description: ARN of the IAM role for the Step Functions state machine

  BucketName:
    Type: String
    Description: Name of the S3 bucket containing the state machine definition

  S3Key:
    Type: String
    Description: Key (path) to the state machine definition file in the S3 bucket

Resources:
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Ref StateMachineName
      DefinitionS3Location:
        Bucket: !Ref BucketName
        Key: !Ref S3Key
      RoleArn: !Ref RoleArn


aws cloudformation create-stack \
  --stack-name YourStateMachineStack \
  --template-body file://path/to/your/template.yaml \
  --parameters \
    ParameterKey=StateMachineName,ParameterValue=YourStateMachineName \
    ParameterKey=RoleArn,ParameterValue=arn:aws:iam::111122223333:role/service-role/YourExecutionRole \
    ParameterKey=BucketName,ParameterValue=your-s3-bucket \
    ParameterKey=S3Key,ParameterValue=path/to/your/hello_world.json



stages:
  - deploy

variables:
  STACK_NAME: YourStateMachineStack
  TEMPLATE_FILE: path/to/your/template.yaml
  AWS_DEFAULT_REGION: your-region
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Set your AWS credentials in GitLab CI/CD environment variables
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  STATE_MACHINE_NAME: YourStateMachineName
  EXECUTION_ROLE_ARN: arn:aws:iam::111122223333:role/service-role/YourExecutionRole
  S3_BUCKET: your-s3-bucket
  S3_KEY: path/to/your/hello_world.json

deploy_stack:
  stage: deploy
  script:
    - |
      if aws cloudformation describe-stacks --stack-name $STACK_NAME 2>/dev/null; then
        echo "Stack already exists. Skipping stack creation."
      else
        aws cloudformation create-stack \
          --stack-name $STACK_NAME \
          --template-body file://$TEMPLATE_FILE \
          --parameters \
            ParameterKey=StateMachineName,ParameterValue=$STATE_MACHINE_NAME \
            ParameterKey=RoleArn,ParameterValue=$EXECUTION_ROLE_ARN \
            ParameterKey=BucketName,ParameterValue=$S3_BUCKET \
            ParameterKey=S3Key,ParameterValue=$S3_KEY
      fi

