AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Include
Description: Include external Step Functions definition file

Resources:
  MyStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      DefinitionString:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: path/to/your/state-machine-definition.json
      Name: MyStateMachineName
      RoleArn: arn:aws:iam::123456789012:role/YourStepFunctionsRole
